=== jSchnitzer1/xmlProcessor/src/main/java/xml/degree/DegreeAndTranscriptSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.hm1.org/schema/DegreeAndTranscript"
            xmlns:tns="http://xml.hm1.org/schema/DegreeAndTranscriptSchema" elementFormDefault="qualified">
    
    <xsd:element name="degreeAndTranscript">
        <xsd:complexType>
            <xsd:sequence>
                
                <xsd:element name="fullStudentName">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:minLength value="1" />
                            <xsd:maxLength value="50" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="personalId">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="[0-9]{8}-[0-9]{4}" /><!-- it can be also \d{8}-\d{4} -->
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="gender">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="male|female"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="school" type="xsd:string" />
                
                <xsd:element name="faculty" type="xsd:string" />
                
                <xsd:element name="address">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:whiteSpace value="replace"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="phone">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="\d+" /> <!-- nonNegativeInteger can be used also -->
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="emailAddress">
                    <xsd:simpleType> 
                        <xsd:restriction base="xsd:string"> 
                            <xsd:pattern value="[^@]+@[^\.]+\..+"/> 
                        </xsd:restriction> 
                    </xsd:simpleType>    
                </xsd:element>

                
                <xsd:element name="graduationDate" type="xsd:date" />
                
                <xsd:element name="academicCourses" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="courseType">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="Mandatory|Elective|Optional"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="course" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="name" type="xsd:string" />

                                        <xsd:element name="code">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="[B-K]{2}\d{4}" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="period">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:integer">
                                                    <xsd:minInclusive value="1" />
                                                    <xsd:maxInclusive value="4" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>

                                        <xsd:element name="mark">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:integer">
                                                    <xsd:minInclusive value="1" />
                                                    <xsd:maxInclusive value="6" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    
                                        <xsd:element name="date" type="xsd:date" />
                                        <xsd:element name="credit">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:float">
                                                    <xsd:minInclusive value="1" />
                                                    <xsd:maxInclusive value="10" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== jSchnitzer1/xmlProcessor/src/main/java/xml/degree/DegreeAndTranscript.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : DegreeAndTranscriptSchema.xml
    Created on : January 28, 2017, 2:05 PM
    Author     : khaled
    Description:
        Purpose of the document follows.
-->

<dt:degreeAndTranscript  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                         xmlns:dt='http://xml.hm1.org/schema/DegreeAndTranscript'
                         xsi:schemaLocation='http://xml.hm1.org/schema/DegreeAndTranscript DegreeAndTranscriptSchema.xsd'>
    
    <dt:fullStudentName>khaled shuang</dt:fullStudentName>
    <dt:personalId>19990101-1111</dt:personalId>
    <dt:gender>male</dt:gender>
    <dt:school>the royal institute of technology</dt:school>
    <dt:faculty>engineering</dt:faculty>
    <dt:address>
        Kista Galleria
        Stockholm
    </dt:address>
    <dt:phone>46739911555</dt:phone>
    <dt:emailAddress>myemail@domain.com</dt:emailAddress>
    <dt:graduationDate>2011-05-05</dt:graduationDate>
    <dt:academicCourses>
        <dt:courseType>Mandatory</dt:courseType>
        <dt:course>
            <dt:name>Concurrent Programming</dt:name>
            <dt:code>ID1111</dt:code>
            <dt:period>1</dt:period>
            <dt:mark>95</dt:mark>
            <dt:date>2010-01-10</dt:date>
            <dt:credit>7.5</dt:credit>
        </dt:course>
        <dt:course>
            <dt:name>Algorithms and Data Structure</dt:name>
            <dt:code>ID7777</dt:code>
            <dt:period>3</dt:period>
            <dt:mark>85</dt:mark>
            <dt:date>2011-01-10</dt:date>
            <dt:credit>7.5</dt:credit>
        </dt:course>
    </dt:academicCourses>
    <dt:academicCourses>
        <dt:courseType>Elective</dt:courseType>
        <dt:course>
            <dt:name>Math 2</dt:name>
            <dt:code>ID5555</dt:code>
            <dt:period>2</dt:period>
            <dt:mark>55</dt:mark>
            <dt:date>2010-05-10</dt:date>
            <dt:credit>6</dt:credit>
        </dt:course>
    </dt:academicCourses>

</dt:degreeAndTranscript>
