=== jSchnitzer1/xmlProcessor/src/main/java/xml/profile/ApplicationProfileSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.hm1.org/schema/ApplicantProfileSchema"
            xmlns:tns="http://xml.hm1.org/schema/ApplicantProfileSchema" elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">Schema for applicant profile. </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="profile">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="cv">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="age" type="xsd:positiveInteger"/>
                            <xsd:element name="tel" minOccurs="0">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\d+"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="email" minOccurs="0">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="address" type="xsd:string" minOccurs="0"/>
                            <xsd:element name="qualifications">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="skill" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="education">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="eduItem" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="degree" type="xsd:string"/>
                                        <xsd:element name="school" type="xsd:string"/>
                                        <xsd:element name="enrollDate" type="xsd:date"/>
                                        <xsd:element name="graduationDate" type="xsd:date"/>
                                        <xsd:element name="GPA" type="xsd:float"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="career">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="careerItem" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="company">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="companyName" type="xsd:string"/>
                                                    <xsd:element name="companyLocation" type="xsd:string"/>
                                                    <xsd:element name="companyTel" type="xsd:string"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="position" type="xsd:string"/>
                                        <xsd:element name="startDate" type="xsd:date"/>
                                        <xsd:element name="endDate" type="xsd:date"/>
                                        <xsd:element name="description" type="xsd:string" minOccurs="0"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="letter" type="xsd:string" minOccurs="0">
                </xsd:element>

                <xsd:element name="preference">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="desirePlace" type="xsd:string"/>
                            <xsd:element name="jobType">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="permanent|intern|summerjob"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== jSchnitzer1/xmlProcessor/src/main/java/xml/profile/ApplicantProfileTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- created by Shuang Qiu -->
<p:profile  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
              xmlns:p='http://xml.hm1.org/schema/ApplicantProfileSchema'
              xsi:schemaLocation='http://xml.hm1.org/schema/ApplicantProfileSchema ../profile/ApplicationProfileSchema.xsd'>
	<!-- cv -->
	<p:cv>
		<p:name>xxx</p:name>
		<p:age>01</p:age>
		<p:tel>999999999</p:tel>
		<p:email>xxx@xxx.xxx</p:email>
		<p:address>xxx, xxx, xxxxxxx</p:address>
		<p:qualifications>
			<p:skill>C, C++, Java, SQL</p:skill>
			<p:skill>English</p:skill>
		</p:qualifications>
	</p:cv>

	<!-- relevant academic degree(s) -->
	<p:education>
		<p:eduItem>
			<p:degree>xxx</p:degree>
			<p:school>KTH</p:school>
			<p:enrollDate>2010-06-01</p:enrollDate>
			<p:graduationDate>2014-08-01</p:graduationDate>
			<p:GPA>84</p:GPA>
		</p:eduItem>
	</p:education>

	<!-- previous working experience -->
	<p:career>
		<p:careerItem>
			<p:company>
				<p:companyName>xxx</p:companyName>
				<p:companyLocation>Stockholm</p:companyLocation>
				<p:companyTel>999-999-999</p:companyTel>
			</p:company>
			<p:position>xxxx</p:position>
			<p:startDate>2016-01-01</p:startDate>
			<p:endDate>2017-01-01</p:endDate>
			<p:description>xxxxxxxxxxxx</p:description>
		</p:careerItem>
	</p:career>

	<!-- Motivation letter -->
	<p:letter>
		xxxx,xxxxx xxx xx xxxxx xxxxxx.
	</p:letter>

	<!-- Preference -->
	<p:preference>
		<p:desirePlace>Stockholm</p:desirePlace>
		<p:jobType>permanent</p:jobType>
	</p:preference>

</p:profile>
