=== jSchnitzer1/xmlProcessor/src/main/java/xml/employment/EmploymentRecordSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.hm1.org/schema/EmploymentRecordSchema"
            xmlns:tns="http://xml.hm1.org/schema/EmploymentRecordSchema" elementFormDefault="qualified">

    <xsd:element name="employmentRecord">
        <xsd:complexType>
            <xsd:sequence>
                
                <xsd:element name="fullEmployeeName">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:minLength value="1" />
                            <xsd:maxLength value="50" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="personalId">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="[0-9]{8}-[0-9]{4}" /><!-- it can be also \d{8}-\d{4} -->
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="gender">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:pattern value="male|female"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="age">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:integer">
                            <xsd:minInclusive value="18" />
                            <xsd:maxInclusive value="65" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="address">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:whiteSpace value="replace"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                
                <xsd:element name="phone" type="xsd:nonNegativeInteger" />
                
                <xsd:element name="emailAddress">
                    <xsd:simpleType> 
                        <xsd:restriction base="xsd:string"> 
                            <xsd:pattern value="[^@]+@[^\.]+\..+"/> 
                        </xsd:restriction> 
                    </xsd:simpleType>    
                </xsd:element>
                
                <xsd:element name="employer" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="employerName" type="xsd:string" />
                            <xsd:element name="employerAddress">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:whiteSpace value="replace"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="position" type="xsd:string" />
                            <xsd:element name="skills" minOccurs="0" maxOccurs="25">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="skillName" type="xsd:string" />
                                        <xsd:element name="proficiency">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:integer">
                                                    <xsd:minInclusive value="1" />
                                                    <xsd:maxInclusive value="10" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="startDate" type="xsd:date" />
                            <xsd:element name="endDate" type="xsd:date" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== jSchnitzer1/xmlProcessor/src/main/java/xml/employment/EmploymentRecord.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : EmploymentRecordSchema.xml
    Created on : January 28, 2017, 2:58 PM
    Author     : khaled
    Description:
        Purpose of the document follows.
-->

<emp:employmentRecord  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                       xmlns:emp='http://xml.hm1.org/schema/EmploymentRecordSchema'
                       xsi:schemaLocation='http://xml.hm1.org/schema/EmploymentRecordSchema EmploymentRecordSchema.xsd'>
    
    <emp:fullEmployeeName>khaled shuang</emp:fullEmployeeName>
    <emp:personalId>19990101-1111</emp:personalId>
    <emp:gender>male</emp:gender>
    <emp:age>25</emp:age>
    <emp:address>
        Kista Galleria
        Stockholm
    </emp:address>
    <emp:phone>46739911555</emp:phone>
    <emp:emailAddress>myemail@domain.com</emp:emailAddress>
    <emp:employer>
        <emp:employerName>MathWorks</emp:employerName>
        <emp:employerAddress>
            Kista
            Stockholm
        </emp:employerAddress>
        <emp:position>Engineer</emp:position>
        <emp:startDate>2011-01-10</emp:startDate>
        <emp:endDate>2012-01-10</emp:endDate>
    </emp:employer>
    <emp:employer>
        <emp:employerName>Volvo</emp:employerName>
        <emp:employerAddress>
            Kista
            Stockholm
        </emp:employerAddress>
        <emp:position>Programmer</emp:position>
        <emp:skills>
            <emp:skillName>C++</emp:skillName>
            <emp:proficiency>7</emp:proficiency>
        </emp:skills>
        <emp:skills>
            <emp:skillName>C#</emp:skillName>
            <emp:proficiency>8</emp:proficiency>
        </emp:skills>
        <emp:skills>
            <emp:skillName>Java</emp:skillName>
            <emp:proficiency>9</emp:proficiency>
        </emp:skills>
        <emp:startDate>2012-01-10</emp:startDate>
        <emp:endDate>2017-01-10</emp:endDate>
    </emp:employer>
</emp:employmentRecord>
