=== jSchnitzer1/xmlProcessor/src/main/java/xml/company/CompanyInfoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.hm1.org/schema/CompanyInfoSchema"
            xmlns:tns="http://xml.hm1.org/schema/CompanyInfoSchema" elementFormDefault="qualified">
    
    <xsd:element name="companyInfo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="company" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            
                            <xsd:element name="name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1" />
                                        <xsd:maxLength value="50" />
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            
                            <xsd:element name="role" type="xsd:string" />
                            
                            <xsd:element name="address">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:whiteSpace value="replace"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                
                            <xsd:element name="phone">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\d+" /> <!-- nonNegativeInteger can be used also -->
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== jSchnitzer1/xmlProcessor/src/main/java/xml/company/CompanyInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : CompanyInfoSchema.xml
    Created on : January 28, 2017, 3:13 PM
    Author     : khaled
    Description:
        Purpose of the document follows.
-->

<c:companyInfo  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                  xmlns:c='http://xml.hm1.org/schema/CompanyInfoSchema'
                  xsi:schemaLocation='http://xml.hm1.org/schema/CompanyInfoSchema CompanyInfoSchema.xsd'>
    
    <c:company>
        <c:name>MathWorks</c:name>
        <c:role>Engineering</c:role>
        <c:address>
            Kista
            Stockholm
        </c:address>
        <c:phone>46739911555</c:phone>
    </c:company>
    <c:company>
        <c:name>Volvo</c:name>
        <c:role>Car Manufacturing</c:role>
        <c:address>
            Kista
            Stockholm
        </c:address>
        <c:phone>46739911555</c:phone>
    </c:company>
</c:companyInfo>
