=== jSchnitzer1/xmlProcessor/src/main/java/xml/shortcv/ShortCVSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://xml.hm1.org/schema/ShortCV"
			xmlns:tns="http://xml.hm1.org/schema/ShortCVSchema" elementFormDefault="qualified">


<xsd:annotation>
		<xsd:documentation xml:lang="en">Schema for applicant upload materials. </xsd:documentation>
	</xsd:annotation>

	<xsd:element name="material">
	<xsd:complexType>
		<xsd:sequence>
			<!-- cv start-->
			<xsd:element name="cv">
				<xsd:complexType>
					<xsd:sequence>
						<!-- basic info start-->
						<xsd:element name="name" type="xsd:string"/>
						<xsd:element name="gender">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:pattern value="male|female"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="address" type="xsd:string" minOccurs="0"/>
						<xsd:element name="tel" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:pattern value="\d{3}-\d{3}-\d{3}"/>
								</xsd:restriction>
						</xsd:simpleType>
						</xsd:element>
						<xsd:element name="email" type="xsd:string" minOccurs="0"/>
						<xsd:element name="website" type="xsd:string" minOccurs="0"/>
						<!-- basic info end -->

						<!-- qualificaitons start-->
						<xsd:element name="qualification">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="skill" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<!-- qualification end -->
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<!-- cv end -->

			<!-- motivation letter start -->
			<xsd:element name="letter" type="xsd:string">
			</xsd:element>
			<!-- motivation letter end -->

			<!-- preferences start -->
			<xsd:element name="preference">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="desirePlace" type="xsd:string"/>
						<xsd:element name="jobType" type="xsd:string"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<!-- preferences end -->
		</xsd:sequence>
		<xsd:attribute name="id" use="required" type="xsd:positiveInteger"/>
		<xsd:attribute name="submitted" use="required" type="xsd:date"/>
	</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== jSchnitzer1/xmlProcessor/src/main/java/xml/shortcv/ShortCV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- using the default namespace material -->

<m:material  id="1" submitted="2017-01-01"
             xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
             xmlns:m='http://xml.hm1.org/schema/ShortCV'
             xsi:schemaLocation='http://xml.hm1.org/schema/ShortCV ShortCVSchema.xsd'>

    <!-- Short CV -->
    <m:cv>
        <m:name>John Smith</m:name>
        <m:gender>male</m:gender>
        <m:address>848 Abbott Road, Stillfield, CT 08888</m:address>
        <m:tel>999-999-999</m:tel>
        <m:email>jsmith@abcd.com</m:email>
        <m:website>jsmith.com</m:website>

        <m:qualification>
            <m:skill>C; C++; Java; C#.NET; SQL</m:skill>
            <m:skill>Speaking, Writing, Design</m:skill>
        </m:qualification>
    </m:cv>

    <!-- Motivation letter -->
    <m:letter>
        Hi there, Iâ€™m Smith. I am a Consultant Front-end Architect, designer,
        developer, writer and speaker from the UK.
    </m:letter>

    <!-- Job preferences -->
    <m:preference>
        <m:desirePlace>Stockholm</m:desirePlace>
        <m:jobType>Permanent</m:jobType>
    </m:preference>


</m:material>
